//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.sampa.tasksreminder;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.CompoundButton.OnCheckedChangeListener;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import com.sampa.tasksreminder.R.id;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class NewTaskActivity_
    extends NewTaskActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static NewTaskActivity_.IntentBuilder_ intent(Context context) {
        return new NewTaskActivity_.IntentBuilder_(context);
    }

    public static NewTaskActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new NewTaskActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        timeReminderButton = ((Button) hasViews.findViewById(id.timeReminderButton));
        reminderInput = ((EditText) hasViews.findViewById(id.reminderInput));
        dateButton = ((Button) hasViews.findViewById(id.dateButton));
        dateReminderButton = ((Button) hasViews.findViewById(id.dateReminderButton));
        reminderSpinner = ((Spinner) hasViews.findViewById(id.reminderSpinner));
        timeButton = ((Button) hasViews.findViewById(id.timeButton));
        toggleReminderCheckBox = ((CheckBox) hasViews.findViewById(id.toggleReminderCheckBox));
        deleteButton = ((Button) hasViews.findViewById(id.deleteButton));
        startReminderText = ((TextView) hasViews.findViewById(id.startReminderText));
        descriptionInput = ((EditText) hasViews.findViewById(id.descriptionInput));
        reminderFrequencyText = ((TextView) hasViews.findViewById(id.reminderFrequencyText));
        titleInput = ((EditText) hasViews.findViewById(id.titleInput));
        {
            View view = hasViews.findViewById(id.dateButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewTaskActivity_.this.chooseDate();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.timeButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewTaskActivity_.this.chooseTime();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.deleteButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewTaskActivity_.this.deleteTask();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.dateReminderButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewTaskActivity_.this.chooseReminderDate();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.timeReminderButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewTaskActivity_.this.chooseReminderTime();
                    }

                }
                );
            }
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.toggleReminderCheckBox));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        NewTaskActivity_.this.checkedChangedOnHelloCheckBox();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(com.sampa.tasksreminder.R.menu.new_task, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        int itemId_ = item.getItemId();
        if (itemId_ == id.accept) {
            accept();
            return true;
        }
        if (itemId_ == id.cancel) {
            cancel();
            return true;
        }
        return false;
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, NewTaskActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, NewTaskActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public NewTaskActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
